dist: xenial

language: python
python:
  - "3.6"

before_install:
  - git clone --recursive https://github.com/dmlc/tvm
  - cd tvm
  # llvm repo
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main"  
  - sudo apt-get update
  # tvm dependencies
  - sudo apt-get install -y python python-dev python-setuptools gcc libtinfo-dev zlib1g-dev
  # llvm
  - sudo apt-get install llvm-6.0

install:
  - mkdir build
  - cp cmake/config.cmake build
  - cd build
  - echo set\(USE_LLVM ON\) >> config.cmake
  - cmake ..
  - make -j3

script: true
